# Run Models
#'
#'
#' This function run many models using the same data
#' @param df   Training dataframe
#' @param formula   A formula of the form y ~ x1 + x2 + ... If users don't inform formula, the first column will be used as Y values and the others columns with x1,x2....xn
#' @param preprocess pre process
#' @param models chosen models to be used to train model. Uses  algortims names from Caret package.
#' @param nfolds   Number of folds to be build in crossvalidation
#' @param repeats repeats
#' @param cpu_cores  Number of CPU cores to be used in parallel processing
#' @param tune_length  This argument is the number of levels for each tuning parameters that should be generated by train
#' @param metric metric used to evaluate model fit. For numeric outcome ("RMSE", "Rsquared)
#' @param seeds  seeds
#' @keywords  models
#' @author Elpidio Filho, \email{elpidio@ufv.br}
#' @details details
#' @export
#' @examples
#' \dontrun{
#' models = c("ridge", "rf", "cubist",'pls','pcr','foba','gbm','glmboost')
#' fit_models = run_models(df,models = models)
#' }

run_models <- function(df,
                       models = c("svmPoly", "rf", "gbm", "C5.0"),
                       formula = NULL,
                       preprocess = NULL,
                       nfolds = 10,
                       repeats = 1,
                       tune_length = 5,
                       cpu_cores = 7,
                       metric = ifelse(is.factor(df[,1]),"Kappa", "Rsquared"),
                       seeds = NULL) {

  if (class(df) != "data.frame") stop("df is not a data frame.")
  package.inicio <- search()[ifelse(unlist(gregexpr("package:", search())) == 1, TRUE, FALSE)]
  inicio = Sys.time()
  if(is.factor(df[,1]) == TRUE) {
    mod = 1
  } else {
    mod = 0
  }
  if (is.null(seeds)) {
    seedsvec = NULL
  } else {
    set.seed(seeds)
    seedsvec <- vector(mode = "list", length = nfolds + 1)
    for (i in 1:nfolds) seedsvec[[i]] <- sample.int(n = 1000, 400)
    seedsvec[[nfolds + 1]] <- sample.int(1000, 1)
  }

  nr = length(models)
  list.model = vector("list", length = nr)
  for (j in 1:length(models)) {
    if (mod == 0) {
      fit.reg = regression(df.train = df,
                           regressor = models[j],
                           preprocess = preprocess,
                           nfolds = nfolds,
                           cpu_cores = cpu_cores,
                           repeats = repeats,
                           metric = metric,
                           tune_length = tune_length,
                           seeds = seedsvec)
      list.model[j] = list(fit.reg)
    }  else {
      fit.class = classification(df.train = df,
                                 classifier = models[j],
                                 preprocess = preprocess,
                                 nfolds = nfolds,
                                 cpu_cores = cpu_cores,
                                 repeats = repeats,
                                 metric = metric,
                                 tune_length = tune_length,
                                 seeds = seedsvec)
      list.model[j] = list(fit.class)
    }
  }
  package.fim =  search()[ifelse(unlist(gregexpr("package:",search())) == 1, TRUE, FALSE)]
  package.list <- setdiff(package.fim, package.inicio)
  if (length(package.list) > 0)  for (package in package.list) detach(package, character.only = TRUE)
  print(paste("time elapsed", round(Sys.time() - inicio, 3)))
  return(list.model)
}
