# Run Models
#'
#'
#' This function run many models using the same data
#' @param df   Training dataframe
#' @param formula   A formula of the form y ~ x1 + x2 + ... If users don't inform formula, the first column will be used as Y values and the others columns with x1,x2....xn
#' @param preprocess pre process
#' @param index  Users cross validation folds. Default = NULL
#' @param models chosen models to be used to train model. Uses  algortims names from Caret package.
#' @param nfolds   Number of folds to be build in crossvalidation
#' @param repeats repeats
#' @param cpu_cores  Number of CPU cores to be used in parallel processing
#' @param tune_length  This argument is the number of levels for each tuning parameters that should be generated by train
#' @param metric metric used to evaluate model fit. For numeric outcome ("RMSE", "Rsquared)
#' @param seeds  seeds
#' @param verbose  prints results during the execution of the function
#' @importFrom progress progress_bar
#' @importFrom utils flush.console
#' @importFrom caret getModelInfo
#' @keywords  models
#' @author Elpidio Filho, \email{elpidio@ufv.br}
#' @details details
#' @export
#' @examples
#' \dontrun{
#' models = c("ridge", "rf", "cubist",'pls','pcr','foba','gbm','glmboost')
#' fit_models = run_models(df,models = models)
#' }




run_models <- function(df, models = ifelse(is.factor(df[, 1]),
                                           c("qda","rf","gbm","C5.0"),
                                           c("lm", "cubist", "gbm", "rf")),
                       formula = NULL,
                       preprocess = NULL,
                       index = NULL,
                       resample = 'cv',
                       nfolds = 10,
                       repeats = NA,
                       tune_length = 5,
                       cpu_cores = 0,
                       metric = ifelse(is.factor(df[, 1]), "Kappa", "Rsquared"),
                       seeds = NULL,
                       verbose = FALSE) {
  if (class(df) != "data.frame") stop("df is not a data frame.")

  for (i in 1:length(models)) {
    md <- getModelInfo(models[i], regex = FALSE)[[1]]
    if (length(md) == 0)
      stop(paste("Model", models[i], "is not in caret's built-in library"), call. = FALSE)
  }

  package.inicio <- search()[ifelse(unlist(gregexpr("package:", search())) == 1, TRUE, FALSE)]
  if (is.factor(df[, 1]) == TRUE) {
    mod <- 1
  } else {
    mod <- 0
  }
  if (verbose == TRUE) {
    pb <- progress_bar$new(total = length(models),
                           format("Running [:bar] :percent elapsed: :elapsed eta: :eta"),
                           clear = FALSE)
    gg <- pb$tick(0)
  }
  nr <- length(models)
  list.model <- vector("list")
  cont <- 1
  for (j in 1:length(models)) {
    if (verbose == TRUE) {
      print(paste("Begin execution model :",models[j]))
      flush.console()
      inicio <- Sys.time()
    }

    if (mod == 0) {
      fit.reg <- tryCatch({
        regression(
          df.train = df,
          index = index,
          resample = resample,
          regressor = models[j],
          preprocess = preprocess,
          nfolds = nfolds,
          cpu_cores = cpu_cores,
          repeats = repeats,
          metric = metric,
          tune_length = tune_length,
          seeds = vector_seeds(seeds, repeats, nfolds))},
        error = function(e){NULL})

      if (is.null(fit.reg) == FALSE ) {
        list.model[cont] <- list(fit.reg)
        names(list.model)[cont] = models[j]
        cont <- cont + 1
      }
    } else {
      fit.class <- tryCatch({
        classification(
          df.train = df,
          index = index,
          classifier = models[j],
          preprocess = preprocess,
          nfolds = nfolds,
          cpu_cores = cpu_cores,
          repeats = repeats,
          metric = metric,
          tune_length = tune_length,
          seeds = vector_seeds(seeds, repeats, nfolds))},
        error = function(e){NULL})
      if (is.null(fit.class) == FALSE ) {
        list.model[cont] <- list(fit.class)
        names(list.model)[cont] = models[j]
        cont <- cont + 1
      }
    }
    if (verbose == TRUE) {
      pb$tick()
    }
  }
  package.fim <- search()[ifelse(unlist(gregexpr("package:", search())) == 1, TRUE, FALSE)]
  package.list <- setdiff(package.fim, package.inicio)
  if (length(package.list) > 0) for (package in package.list) detach(package, character.only = TRUE)
  list.model <- list.model[!sapply(list.model, is.null)]
  return(list.model)
}



vector_seeds <- function(seeds, repeats, nfolds){
  if (is.null(seeds)) {
    vseed <- NULL
  } else {
    set.seed(seeds)
    if (is.na(repeats) == FALSE) {
      nel <- nfolds * repeats + 1
    } else {
      nel <- nfolds + 1
    }
    vseed <- vector(mode = "list", length = nel)
    for (i in 1:nel) vseed[[i]] <- sample.int(n = 5000, nel * 10)
    vseed[[nel + 1]] <- sample.int(5000, 1)
  }
  return(vseed)
}
